import React, { useState } from 'react';
import { useStore } from '../../context/StoreContext';
import { formatCurrency } from '../../lib/utils';
import { Button } from '../../components/ui/Button';
import { Download, Filter, FileText, Calendar } from 'lucide-react';
import { Product, Order } from '../../types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const Reports = () => {
  const { orders } = useStore();
  const [reportType, setReportType] = useState<'Weekly Sales Report' | 'Monthly Sales Report' | 'Yearly Sales Report'>('Monthly Sales Report');
  const [selectedCategory, setSelectedCategory] = useState<string>('All Categories');
  const [isGenerating, setIsGenerating] = useState(false);

  const categories = ['All Categories', 'Shirts', 'T-Shirts', 'Jeans', 'Party Wear', 'Ethnic Wear'];

  // Mock data generation for charts based on real orders
  // In a real app, this would be aggregated from the 'orders' array
  const allData = [
    { name: 'Shirts', sales: 4000 },
    { name: 'Jeans', sales: 3000 },
    { name: 'T-Shirts', sales: 2000 },
    { name: 'Party Wear', sales: 2780 },
    { name: 'Ethnic Wear', sales: 1890 },
  ];

  // Filter data based on selected category
  const data = selectedCategory === 'All Categories' 
    ? allData 
    : allData.filter(item => item.name === selectedCategory);

  const totalSales = orders.reduce((acc, o) => acc + o.totalAmount, 0);
  const totalOrders = orders.length;

  const handleDownload = () => {
    setIsGenerating(true);
    
    // Use setTimeout to allow the UI to update (show loading state) before heavy sync work
    setTimeout(() => {
      try {
        const doc = new jsPDF();
        
        // -- Header --
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text("KM Fashion Clothing Co.", 14, 22);
        
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text("Internal Sales Report", 14, 30);
        
        // -- Report Info --
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 35, 196, 35); // Horizontal line
        
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text(`Report Type: ${reportType}`, 14, 45);
        doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 50);
        doc.text(`Generated By: Product Manager`, 14, 55);

        // -- Summary Section --
        doc.setFillColor(245, 247, 250);
        doc.rect(14, 60, 182, 25, 'F');
        
        doc.setFontSize(11);
        doc.text("Summary Overview", 20, 70);
        
        doc.setFontSize(10);
        doc.text(`Total Orders: ${totalOrders}`, 20, 80);
        // Note: Using "INR" instead of symbol to avoid font encoding issues in standard PDF fonts
        doc.text(`Total Revenue: INR ${totalSales.toLocaleString('en-IN')}`, 100, 80);

        // -- Table Section --
        const tableColumn = ["Category", "Sales Units (Est)", "Revenue (INR)"];
        const tableRows = data.map(item => [
          item.name,
          Math.floor(item.sales / 500), // Mock unit count
          item.sales.toLocaleString('en-IN')
        ]);

        autoTable(doc, {
          startY: 95,
          head: [tableColumn],
          body: tableRows,
          theme: 'grid',
          headStyles: { fillColor: [79, 70, 229] }, // Indigo color
          styles: { fontSize: 10 },
        });

        // -- Footer --
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text('Confidential - Internal Use Only', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, 180, doc.internal.pageSize.height - 10);
        }

        // Save the PDF
        doc.save(`${reportType.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
      } catch (error) {
        console.error("Error generating PDF:", error);
        alert("Failed to generate PDF. Please try again.");
      } finally {
        setIsGenerating(false);
      }
    }, 500);
  };

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-800 mb-6">Reports & Analytics</h1>

      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100 mb-8">
        <div className="flex flex-wrap items-end gap-4 mb-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Report Type</label>
            <select 
              className="border border-gray-300 rounded-md px-3 py-2 w-48 focus:ring-2 focus:ring-emerald-500 outline-none"
              value={reportType}
              onChange={(e) => setReportType(e.target.value as any)}
            >
              <option>Weekly Sales Report</option>
              <option>Monthly Sales Report</option>
              <option>Yearly Sales Report</option>
            </select>
          </div>
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Category Filter</label>
            <select 
              className="border border-gray-300 rounded-md px-3 py-2 w-48 focus:ring-2 focus:ring-emerald-500 outline-none"
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
            >
              {categories.map(category => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
          </div>

          <Button onClick={handleDownload} isLoading={isGenerating}>
            <Download className="w-4 h-4 mr-2" /> 
            {isGenerating ? 'Generating PDF...' : 'Generate & Download PDF'}
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
            <p className="text-sm text-gray-500">Total Revenue</p>
            <p className="text-2xl font-bold text-gray-900">{formatCurrency(totalSales)}</p>
          </div>
          <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
            <p className="text-sm text-gray-500">Total Orders</p>
            <p className="text-2xl font-bold text-gray-900">{totalOrders}</p>
          </div>
          <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
            <p className="text-sm text-gray-500">Top Category</p>
            <p className="text-2xl font-bold text-gray-900">Shirts</p>
          </div>
        </div>

        <div className="h-[300px] w-full">
          <h3 className="font-bold text-gray-700 mb-4">
            {selectedCategory === 'All Categories' 
              ? 'Category-wise Sales Performance' 
              : `${selectedCategory} Sales Performance`}
          </h3>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip formatter={(value) => formatCurrency(value as number)} />
              <Legend />
              <Bar dataKey="sales" fill="#10b981" name="Sales Amount (₹)" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};
